spring.application.name=demo
server.port = 8082
spring.profiles.active=dev

spring.jackson.time-zone=America/Guayaquil

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.demo.infrastructure.config=DEBUG

# Keycloak OIDC Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/SpringSecurityLab
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/SpringSecurityLab/protocol/openid-connect/certs

app.security.public-endpoints[0]=/swagger-ui/**
app.security.public-endpoints[1]=/v3/api-docs/**
app.security.role-prefix=ROLE_

app.security.keycloak.client-id=irrigation-suggester-app
app.security.keycloak.resource-access-claim=resource-access
app.security.keycloak.roles-claim=roles